export const posts = [
	{
		id: "3453fd45dsg",
		title: "Lorem ipsum dolor 1",
		creation_date: "20-12-2022",
		content:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.",
		image: "https://via.placeholder.com/450x300",
	},
	{
		id: "3453fd4534fdgds5dsg",
		title: "Lorem ipsum dolor 1",
		creation_date: "20-12-2022",
		content:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.",
		image: "https://via.placeholder.com/450x300",
	},
	{
		id: "3453fsd45345g",
		title: "Lorem ipsum dolor 1",
		creation_date: "20-12-2022",
		content:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.",
		image: "https://via.placeholder.com/450x300",
	},
	{
		id: "3453f454gfd345g",
		title: "Lorem ipsum dolor 1",
		creation_date: "20-12-2022",
		content:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae. Lorem donec massa sapien faucibus et. Lorem donec massa sapien faucibus et molestie ac feugiat. Aliquam ut porttitor leo a diam. Sit amet cursus sit amet. Sit amet cursus sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ullamcorper morbi tincidunt ornare massa eget egestas purus.",
		image: "https://via.placeholder.com/450x300",
	},
];
