export const data = [
	{	serial: 1,   
		name: "Lorem ipsum dolor sit amet",
		year: "2022",
		award: "Dolor sit amet",
	},
	{	serial: 2,
		name: "Lorem ipsum dolor sit amet",
		year: "2020",
		award: "Dolor sit amet",
	},
	{	serial: 3,
		name: "Lorem ipsum dolor sit amet",
		year: "2021",
		award: "Dolor sit amet",
	},
	{	serial: 4,
		name: "Lorem ipsum dolor sit amet",
		year: "2022",
		award: "Dolor sit amet",
	},
	{	serial: 5,
		name: "Lorem ipsum dolor sit amet",
		year: "2018",
		award: "Dolor sit amet",
	},
	{	serial: 6,
		name: "Lorem ipsum dolor sit amet",
		year: "2019",
		award: "Dolor sit amet",
	},
	{	serial: 7,
		name: "Lorem ipsum dolor sit amet",
		year: "2018",
		award: "Dolor sit amet",
	},
	{	serial: 8,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	},
	{	serial: 9,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	},
	{	serial: 10,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	},{	serial: 11,   
		name: "Lorem ipsum dolor sit amet",
		year: "2022",
		award: "Dolor sit amet",
	},
	{	serial: 12,
		name: "Lorem ipsum dolor sit amet",
		year: "2020",
		award: "Dolor sit amet",
	},
	{	serial: 13,
		name: "Lorem ipsum dolor sit amet",
		year: "2021",
		award: "Dolor sit amet",
	},
	{	serial: 14,
		name: "Lorem ipsum dolor sit amet",
		year: "2022",
		award: "Dolor sit amet",
	},
	{	serial: 15,
		name: "Lorem ipsum dolor sit amet",
		year: "2018",
		award: "Dolor sit amet",
	},
	{	serial: 16,
		name: "Lorem ipsum dolor sit amet",
		year: "2019",
		award: "Dolor sit amet",
	},
	{	serial: 17,
		name: "Lorem ipsum dolor sit amet",
		year: "2018",
		award: "Dolor sit amet",
	},
	{	serial: 18,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	},
	{	serial: 19,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	},
	{	serial: 20,
		name: "Lorem ipsum dolor sit amet",
		year: "2017",
		award: "Dolor sit amet",
	}
];
